### ISSUE TITLE
iCub MED-ical 10/2/2023

### ISSUE THREAD

**Issue by arrenglover** [event-driven-robotics/event-driven-demos#7]
@LZC-68 , @Iaxama , @p0uya-a , @stefanochi , @arrenglover 

# Medical

- [ ] open issue for not-starting boards (Massi)
- [x] follow up with Maurizio for camera FPGA (Arren)
- [x] double check "how to update firmware", and add "how to update software" to the same readme (Stefano)
  - [x] should our software version be always "master" or should we follow a distribution [here](https://icub-tech-iit.github.io/documentation/sw_versioning_table/#software-versioning-table)
  - [x] should `icub-firmware-build` be in `robotology-superbuild` or is a separate repository
- [x] add "icub-MED" readme - what to do for each day (Arren)
- [x] disc space on ultrascale was filled. used BAOBAB to find big files and clean-out.
  - [ ] should we have a bigger SD card for the ultrascale? 

# Education

- [x] explain computer network environment, yarp server,  and how to start the robot etc. - Massi
- [x] explain some code for controlling the robot in code - Massi
- [x] Here are some more instructions on [YARP](https://yarp.it/latest//)

# Demos

- [x] Massi ran the new inverse kinematics with the quadratic solver suggested by dynamics guys on the real robot

# TODO

- [ ] Zynqgrabber vPreProcess integration
- [ ] fixing on/off camera problem in zynqGrabber
- [ ] follow up with Maurizio for FPGA problems
- [ ] start on ball tracking demo
